<?php $this->view('/components/header'); ?>

<section class="advert">
	<div class="container">
		<div class="content">
			<h2 class="content__head-item">Добавить объявление</h2>
			<p class="content__info-item">
				Заполните форму ниже, для того чтобы добавить объявление на сайт
			</p>

			<div class="content__item-section">
        <form action="" method="post" class="form">
          <div class="form-group">
						<?php if( isset($errors['name']) ): ?>
							<span class="error-message"><?= implode('<br>', $errors['name']) ?></span>
						<?php endif; ?>
            <label class="form__label-name">Название</label>
            <input class="form-control" type="text" name="name">
          </div>
          <div class="form-group">
						<?php if( isset($errors['descr']) ): ?>
							<span class="error-message"><?= implode('<br>', $errors['descr']) ?></span>
						<?php endif; ?>
            <label class="form__label-description">Описание</label>
            <textarea class="form-control" rows="3" name="descr"></textarea>
          </div>
          <div class="form-group">
						<?php if( isset($errors['image']) ): ?>
							<span class="error-message"><?= implode('<br>', $errors['image']) ?></span>
						<?php endif; ?>
            <label class="form__label-image">Изображение</label>
            <input class="form-file" type="file" name="img">
          </div>
          <button type="submit" class="btn btn--black">Добавить</button>
        </form>
			</div>
		</div>
	</div>
</section>

<?php $this->view('/components/footer'); ?>