<?php $this->view('/components/header'); ?>

<section class="advert">
	<div class="container">
		<div class="content">
			<h2 class="content__head-item">Добавить объявление</h2>
			<p class="content__info-item">
				Заполните форму ниже, для того чтобы добавить объявление на сайт
			</p>

			<div class="content__item-section">
        <form action="" method="post" class="form">
          <div class="form-group">
						<?php if( isset($errors['name']) ): ?>
							<span class="error-message"><?= implode('<br>', $errors['name']) ?></span>
						<?php endif; ?>
            <label class="form__label-name">Название</label>
            <input class="form-control" type="text" name="name" value="<?= $name ?>" required="required">
          </div>
          <div class="form-group">
						<?php if( isset($errors['descr']) ): ?>
							<span class="error-message"><?= implode('<br>', $errors['descr']) ?></span>
						<?php endif; ?>
            <label class="form__label-description">Описание</label>
            <textarea class="form-control" rows="3" name="descr" required="required"></textarea>
          </div>
          <div class="form-group form-group--double__block">
						<?php if( isset($errors['image']) ): ?>
							<span class="error-message"><?= implode('<br>', $errors['image']) ?></span>
						<?php endif; ?>
						<div class="img-block">
	            <label class="form__label-image">Изображение</label>
	            <input class="form-file" type="file" name="img">
						</div>
						<div class="select-block">
	          	<label class="form-select__description">Выберите категорию</label>
	          	<select name="cat" class="form__select-item form-control" required="required" size="1">
	          		<optgroup label="Автомобили" class="form__optgroup-item">
		          		<option value="cat1" class="form__option-item">Категория 1</option>
		          		<option value="cat2" class="form__option-item">Категория 2</option>
		          		<option value="cat3" class="form__option-item">Категория 3</option>
		          		<option value="cat4" class="form__option-item">Категория 4</option>
	          		</optgroup>
	          		<optgroup label="Телевизоры" class="form__optgroup-item">
		          		<option value="cat5" class="form__option-item">Категория 1</option>
		          		<option value="cat6" class="form__option-item">Категория 2</option>
		          		<option value="cat7" class="form__option-item">Категория 3</option>
		          		<option value="cat8" class="form__option-item">Категория 4</option>
	          		</optgroup>
	          	</select>
						</div>
          </div>
          <button type="submit" class="btn btn--black">Добавить</button>
        </form>
			</div>
		</div>
	</div>
</section>

<?php $this->view('/components/footer'); ?>