<?php $this->view('header'); ?>

<section class="personal-kab">
	<div class="container">
		<div class="content tabs">
			<h2 class="content__head-item">Персональный кабинет</h2>
			
			<aside class="content__aside-section">
				<p class="user-menu__head-item">меню пользователя</p>
				<ul class="user-list tab-nav">
					<li class="user-list__item">
						<i class="fa fa-user-o user-list__icon-item" aria-hidden="true"></i>
							<span class="user-name"><?= $_SESSION['user']['name']?></span>
					</li>
					<li class="user-list__item tap-me">
						<i class="fa fa-heart-o user-list__icon-item" aria-hidden="true"></i>
							<span>Избранное</span>
					</li>
					<li class="user-list__item tap-me">
						<i class="fa fa-pencil-square-o user-list__icon-item" aria-hidden="true"></i>
							<span>Добавить объявление</span>
					</li>
				</ul>
			</aside>

			<div class="content__item-section">
				<!-- первая вкладка -->
				<div class="tabs-item">
	        <?php /* foreach ($items as $item):?>
		        <div class="card-item">
		          <header class="card-head">
		            <a class="image-popup-vertical-fit" href="<?= $item['image'] ?>">
		              <img src="<?= $item['image'] ?>" alt="image" class="head-image">
		            </a>

		            <p class="product-description">
		              <?= e($item['title'])?>
		            </p>
		          </header>

		          <div class="card-body">
		            <a href="#box-popup-anim" class="card-item__txt popup-modal">
		              <?= e($item['descr'])?>
		            </a>
		            <div id="box-popup-anim" class="modal-popup mfp-hide">
		              <button class="popup-modal-dismiss">
		                <i class="fa fa-times popup-icon" aria-hidden="true"></i>
		              </button>

		              <div class="popup-content">
		                <h3 class="popup-heading"><?= e($item['title'])?></h3>
		                <p class="popup-txt">
		                  <?= e($item['descr'])?>
		                </p>
		              </div>
		              
		            </div>
		          </div>

		          <div class="card-tools">
		            <button class="btn-favorites">
		              <i class="fa fa-heart-o icon-circle" aria-hidden="true"></i>
		            </button>
		          </div>
		        </div>
	        <?php endforeach; */?>
        </div>

        <!-- вторая вкладка -->
        <div class="tabs-item">
          <form action="" method="post" class="form">
            <div class="form-group">
              <label class="form__label-name">Название</label>
              <input class="form-control" type="text" name="name">
            </div>
            <div class="form-group">
              <label class="form__label-description">Описание</label>
              <textarea class="form-control" rows="3" name="text"></textarea>
            </div>
            <div class="form-group">
              <label class="form__label-image">Изображение</label>
              <input class="form-file" type="file" name="img">
            </div>
            <button type="submit" class="btn btn--black">Добавить</button>
          </form>
        </div>
			</div>
		</div>
	</div>
</section>

<?php $this->view('footer'); ?>