<?php $this->view('/components/header'); ?>

<section class="category-add">
	<div class="container">
		<div class="content">
			<h2 class="content__head-item">Управление категориями</h2>
			<p class="content__info-item">
				Заполните форму ниже, для того чтобы добавить категорию в базу данных
			</p>

			<div class="cat-settings">
				<form action="" method="post" class="form" accept-charset="utf-8">
          <div class="form-group">
          	<p class="cat-name__head">Добавить категорию</p>
          	<label class="cat-name__label-item">
          		<span class="cat-name__info">Название категории</span>
							<?php if( isset($errors['cat_name']) ): ?>
								<span class="error-message"><?= implode('<br>', $errors['cat_name']) ?></span>
							<?php endif; ?>
          		<input class="form-control" name="cat_name" id="cat_name" type="text" value="">
          	</label>
          	<label class="cat-name__label-item">
          		<span class="cat-name__info">Название подкатегории</span>
							<?php if( isset($errors['subcat_name']) ): ?>
								<span class="error-message"><?= implode('<br>', $errors['subcat_name']) ?></span>
							<?php endif; ?>
          		<input class="form-control" name="subcat_name" id="subcat_name" type="text" value="">
          	</label>
          </div>
          <button type="submit" name="submit" class="btn btn--black btn--add-mod">Добавить</button>
				</form>

				<form action="" method="post" class="form">
					<div class="form-group form-group__head">
						<p class="cat-name__head">Удаление категории</p>
						<span class="cat-name__subhead">Выберите категорию для удаления</span>
					</div>
					<div class="form-group form-group__body">
	        	<select name="cat" class="form__select-item form-control" required size="1">
	        		<optgroup label="Автомобили" class="form__optgroup-item">
	          		<option value="cat1" class="form__option-item">Категория 1</option>
	          		<option value="cat2" class="form__option-item">Категория 2</option>
	          		<option value="cat3" class="form__option-item">Категория 3</option>
	          		<option value="cat4" class="form__option-item">Категория 4</option>
	        		</optgroup>
	        		<optgroup label="Телевизоры" class="form__optgroup-item">
	          		<option value="cat5" class="form__option-item">Категория 1</option>
	          		<option value="cat6" class="form__option-item">Категория 2</option>
	          		<option value="cat7" class="form__option-item">Категория 3</option>
	          		<option value="cat8" class="form__option-item">Категория 4</option>
	        		</optgroup>
	        	</select>
	        	<button type="submit" name="submit" class="btn btn--black btn--delete-mod">Удалить</button>
        	</div>
				</form>
			</div>
		</div>
	</div>
</section>

<?php $this->view('/components/footer'); ?>