<!DOCTYPE html>
<html lang="ru">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width,initial-scale=1">
	<title>Document</title>
		<!-- my stylesheets -->
  <link rel="stylesheet" type="text/css" href="/css/libs.min.css">
  <link rel="stylesheet" type="text/css" href="/css/main.min.css">

</head>
<body>
<header class="header">
  <div class="container">
    <div class="header-content">
      <div class="socialmedia-block">
        <ul class="social-media">
          <li class="social-media__li">
            <a href="#" class="social-media__link" target="_blank"><i class="fa fa-telegram social-icons tg" aria-hidden="true"></i></a>
          </li>
          <li class="social-media__li">
            <a href="#" class="social-media__link" target="_blank"><i class="fa fa-facebook-square social-icons fb" aria-hidden="true"></i></a>
          </li>
          <li class="social-media__li">
            <a href="#" class="social-media__link" target="_blank"><i class="fa fa-vk social-icons vk" aria-hidden="true"></i></a>
          </li>
        </ul>
      </div>

      <div class="account-setting">
        <div class="dropdown-menu">
          <button class="btn-open">
            <i class="fa fa-bars" aria-hidden="true"></i>
          </button>
          <nav class="menu-content account-setting__navigation">
            <?php if( isset($_SESSION['user']) ): ?>
              <ul class="counter-bar">
                <li class="counter-bar__li-item">
                  <a href="#" target="_blank" class="counter-bar__link-item">
                    <i class="fa fa-heart-o counter-bar__icon-item" aria-hidden="true"></i>
                      <span class="fav-counter">5</span>
                  </a>
                </li>
              </ul>
            <?php endif; ?>

            <?php if( isset($_SESSION['user']) ): ?>
              <a href="/" target="_blank" class="account-setting__link general-page">
                <i class="fa fa-home link-icon" aria-hidden="true"></i>
                <span class="link-txt">На главную</span>
              </a>
              <a href="/user/cabinet" target="_blank" class="account-setting__link kabinet">
                <i class="fa fa-user-circle-o link-icon" aria-hidden="true"></i>
                <span class="link-txt">Персональный кабинет</span>
              </a>
              <a href="/user/logout" class="account-setting__link unlogin">
                <i class="fa fa-sign-out link-icon" aria-hidden="true"></i>
                <span class="link-txt">Выход</span>
              </a>
            <?php else: ?>
              <a href="/user/login" class="account-setting__link login">
                <i class="fa fa-sign-in link-icon" aria-hidden="true"></i>
                <span class="link-txt">Вход</span>
              </a>
              <a href="/user/register" target="_blank" class="account-setting__link register">
                <i class="fa fa-user-plus link-icon" aria-hidden="true"></i>
                <span class="link-txt">Регистрация</span>
              </a>            
            <?php endif; ?>
          </nav>
        </div>
      </div>
    </div>
  </div>
</header>

<div class="wrapper">
	<main class="main-content">