<?php $this->view('/components/header'); ?>
<section class="items-section">
  <div class="container">
    <div class="content">
      <aside class="content-sidebar">
        <nav class="content-sidebar__nav-item">
          <?php $this->view('/components/multi-menu'); ?>
        </nav>
      </aside>

      <div class="box-items">
        <?php foreach ($items as $item):?>
          <div class="card-item">
            <header class="card-head">
              <a class="image-popup-vertical-fit" href="<?= $item['image'] ?>">
                <img src="<?= $item['image'] ?>" alt="image" class="head-image">
              </a>

              <p class="product-description">
                <?= e($item['title'])?>
              </p>
            </header>

            <div class="card-body">
              <a href="#box-popup-anim" class="card-item__txt popup-modal">
                <?= e($item['descr'])?>
              </a>
              <div id="box-popup-anim" class="modal-popup mfp-hide">
                <button class="popup-modal-dismiss">
                  <i class="fa fa-times popup-icon" aria-hidden="true"></i>
                </button>

                <div class="popup-content">
                  <h3 class="popup-heading"><?= e($item['title'])?></h3>
                  <p class="popup-txt">
                    <?= e($item['descr'])?>
                  </p>
                </div>
                
              </div>
            </div>

            <div class="card-tools">
              <button class="btn-favorites">
                <i class="fa fa-heart-o icon-circle" aria-hidden="true"></i>
              </button>
            </div>
          </div>
        <?php endforeach;?>
      </div>

    </div>
  </div>
</section>
<?php $this->view('/components/footer'); ?>
<script>
  $(function(){
    /*Инициализация плагина*/
    $('.harmonica-menu').liHarmonica({
      onlyOne: true,
      speed: 400,
      badge: true,
      arrow: true
    });
  });
</script>