<?php $this->view('/components/header'); ?>
<section class="user-login">
	<div class="container">
		<div class="row">
			<form class="form" action="" method="post" accept-charset="utf-8">
				<div class="form-group">
					<label class="form-label__item" for="email">Введите email:</label>
						<?php if( isset($errors['email']) ): ?>
							<span class="error-message"><?= implode('<br>', $errors['email']) ?></span>
						<?php endif; ?>
						<input class="form-input__item" id="email" type="text" name="email" value="<?= $email ?>">		
				</div>

				<div class="form-group">
					<label class="form-label__item" for="pass">Введите пароль:</label>
						<?php if( isset($errors['pass']) ): ?>
							<span class="error-message"><?= implode('<br>', $errors['pass']) ?></span>
						<?php endif; ?>
						<input class="form-input__item" id="pass" type="password" name="pass" value="">
				</div>

				<div class="form-group">
					<label class="form-label__item">
						<span>Запомнить меня</span>
						<input name="remember" type="checkbox" value="1"<?php if( $remember ){echo ' checked';} ?>>
					</label>
				</div>
				
				<input class="btn btn--black" name="submit" type="submit" value="войти">
			</form>

		</div>
	</div>
</section>
<?php $this->view('/components/footer'); ?>