	</main>
</div>

<footer class="footer">
  <div class="container">
    <div class="row">
      <div class="info-box">
        <h3 class="info-box__item-head">Ищите нас:</h3>
        <ul class="social-media">
          <li class="social-media__li">
            <a href="#" class="social-media__link" target="_blank"><i class="fa fa-telegram social-icons tg" aria-hidden="true"></i></a>
          </li>
          <li class="social-media__li">
            <a href="#" class="social-media__link" target="_blank"><i class="fa fa-facebook-square social-icons fb" aria-hidden="true"></i></a>
          </li>
          <li class="social-media__li">
            <a href="#" class="social-media__link" target="_blank"><i class="fa fa-vk social-icons vk" aria-hidden="true"></i></a>
          </li>
        </ul>
      </div>
      
      <div class="copyright-box">
        <p class="copyright">&copy; 2020 NИ</p>
        <div class="semantic-block">
          <a href="http://jigsaw.w3.org/css-validator/check/referer">
            <img style="border:0;width:88px;height:31px"
              src="http://jigsaw.w3.org/css-validator/images/vcss"
              alt="Правильный CSS!" />
          </a> 
        </div>
      </div>
    </div>
  </div>
</footer>

		<!-- script's -onn -->
 <script src="/script/libs.js"></script>
 <script src="/frontend/js/common.js"></script>

		<!-- script's -off -->
</body>
</html>