<ul class="harmonica-menu" id="list">
  <li class="cat-name"><a href="#">Автомобили</a>
    <ul class="harmonica-subcontent">
      <li class="item-name"><a href="#">DMC</a>
        <ul class="harmonica-subcontent">
          <li class="model-name"><a href="#">Модель 1</a></li>
          <li class="model-name"><a href="#">Модель 2</a></li>
          <li class="model-name"><a href="#">Модель 3</a></li>
          <li class="model-name"><a href="#">Модель 4</a></li>
        </ul>
      </li>

      <li class="item-name"><a href="#">Damas</a></li>
    </ul>
  </li>

  <li class="cat-name"><a href="#">Телевизоры</a>
    <ul class="harmonica-subcontent">
      <li class="item-name"><a href="#">LG</a>
        <ul class="harmonica-subcontent">
          <li class="model-name"><a href="#">Модель 1</a></li>
          <li class="model-name"><a href="#">Модель 2</a></li>
          <li class="model-name"><a href="#">Модель 3</a></li>
        </ul>
      </li>
    </ul>
  </li>

</ul>